# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - webchat-mockbot2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Repackage
        run: |
          npm pack
          tar xvf *.tgz
          mv node_modules package
          cd package
          ls -la
          zip -1rq ../zipdeploy.zip .

      - name: Upload artifact (tarball)
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.tgz'

      - name: Upload artifact (Zip Deploy)
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: zipdeploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Unzip artifact
        run: |
          unzip zipdeploy.zip
          rm zipdeploy.zip
          ls -la

      # - name: 'Deploy to Azure Web App'
      #   id: deploy
      #   uses: azure/webapps-deploy@v1
      #   with:
      #     app-name: 'webchat-mockbot2'
      #     slot-name: 'production'
      #     publish-profile: ${{ secrets.AzureAppService_PublishProfile_774a167ab81e4bafb6507401dfdc8b26 }}
      #     package: zipdeploy.zip

      # - name: 'Ping deployment'
      #   run: |
      #     curl -s ${{ steps.deploy.outputs.webapp-url }}/health.txt
      #     curl -s ${{ steps.deploy.outputs.webapp-url }}/ready.txt
